### ISSUE TITLE
Add teleport options to "Player" tab and make it more visual which portals are available

### ISSUE THREAD

**Issue by Feedy88** [Puresyn/KeyMaster#29]
**Is your feature request related to a problem? Please describe.**
Not particular a major problem. Within the Party-Frame the fuctionality exists already but it could use some more highlighting which portals are available without hover (e.g. shimmering border, small portal icon in the corner...). I am aware this is a nit, as the complered ratings are below and a +20 should be spottable just fine.

However, I think adding them to the player tab would be an improvement.

**Describe the solution you'd like**
In the player tab, Alt (or other mod) + Click will use the teleport-function to teleport to the dungeon

**Describe alternatives you've considered**
As mentioned, functionality is already given in Group-Tab

**Additional context**
n/a

**Comment by Feedy88** [comment]
That is a valid point and probably doesn't match effort for the value.

As this was two requests, I would still fall back to the second part:

Describe the solution you'd like
In the Party-Tab, add a visual to see which teleport are available to my character without having to hover. Preferred solution: Little Teleport icon (e.g. [this](https://camo.githubusercontent.com/b3ca1215078060bf3b7d838a085cf8e2514d8b549c980c95cd393e0cc108731f/68747470733a2f2f692e696d6775722e636f6d2f4e4955713974612e706e67) which is commonly used by other addons like handy notes)

**Comment by Puresyn** [comment]
Yes, a bit more of a visual queue on portals has been requested before and it is something we are exploring. We are not sure when exactly that might be implemented but it is on our list of things to look into in the near future. Thanks again for the feedback!
