### ISSUE TITLE
Addon causes "You aren't in a party." message to appear in lfg

### ISSUE THREAD

**Issue by magisterszymek** [Puresyn/KeyMaster#30]
Addon causes "You aren't in a party." message to appear in lfg content for example in random timewalking.

1. Join any lfg content (random heroic, random dungeon, random timewalking) with addon turn on
2. A lot of "You aren't in a party." messages will appear at the start

The messages also seems to appear every time you kill a boss or player leaves in lfg content.

**Expected behavior**
There shouldn't be any messages.

![Screenshot 2024-04-03 220406](https://github.com/Puresyn/KeyMaster/assets/35369564/c22372c1-0aae-4066-8898-738575bf725a)
![Screenshot 2024-04-03 235237](https://github.com/Puresyn/KeyMaster/assets/35369564/265acd99-1d46-4a0f-adda-86a1a078945f)
![Screenshot 2024-04-03 235214](https://github.com/Puresyn/KeyMaster/assets/35369564/dd4662f3-26f2-4386-8f64-9f0c22fb698b)

**Comment by Puresyn** [comment]
Thanks for the report! I've personally seen this before but wasn't sure it was KM doing it. We'll dig into it! Thanks!

**Comment by Puresyn** [comment]
Fixed
