### ISSUE TITLE
Dungeon Teleports don't work

### ISSUE THREAD

**Issue by Floppy012** [Puresyn/KeyMaster#38]
**Describe the bug**
When clicking on the dungeon portals in the party section nothing happens. 

This is not working since I have installed the addon at the start of this season (DF4). At first the window closed immediately, since the last update it just does nothing. I have all portals of the current dungeons unlocked (in S1 and S2). No error is shown.

**To Reproduce**
1. Open KeyMaster
2. Go to "Party"
3. Click on a dungeon portal

**Expected behavior**
The cast of the teleport to the clicked dungeon should start

**Screenshots**
-

**Additional context**
-

**Comment by Puresyn** [comment]
Thanks for the report. We'll look into it.

**Comment by Puresyn** [comment]
Additionally, what is the client language? English US? Or, something else?

**Comment by Floppy012** [comment]
Yes 1.1.3. Client language is English US. If you need more info (logs, etc), hit me up

**Comment by Puresyn** [comment]
> Yes 1.1.3. Client language is English US. If you need more info (logs, etc), hit me up

Could you hit me up in discord? https://discord.gg/RvBWA5pe

**Comment by Puresyn** [comment]
Determined to be an OPie addon mouse click over-ride issue. This has been addressed in >= 1.1.4
