### ISSUE TITLE
[Development 1.2] -> Core/UI/ChallengeCompletionMapping.lua:241

### ISSUE THREAD

**Issue by Hollicsh** [Puresyn/KeyMaster#42]
1x ...Ons/KeyMaster/Core/UI/ChallengeCompletionMapping.lua:241: attempt to get length of local 'challengeInfo' (a number value)
[string "@KeyMaster/Core/UI/ChallengeCompletionMapping.lua"]:241: in function `GetCompletionInfoWithRetries'
[string "@KeyMaster/Libs/Internal/EventHooks.lua"]:103: in function <KeyMaster/Libs/Internal/EventHooks.lua:50>
[string "@KeyMaster/Libs/Internal/EventHooks.lua"]:155: in function <KeyMaster/Libs/Internal/EventHooks.lua:121>

Locals:
self = <table> {
 createMemberRows = <function> defined @KeyMaster/Core/UI/ChallengeCompletion.lua:29
 CreateChallengeBanner = <function> defined @KeyMaster/Core/UI/ChallengeCompletionMapping.lua:231
 getDummyData = <function> defined @KeyMaster/Core/UI/ChallengeCompletionMapping.lua:11
 GetCompletionInfoWithRetries = <function> defined @KeyMaster/Core/UI/ChallengeCompletionMapping.lua:235
 ChallengeCompletionFrame = <function> defined @KeyMaster/Core/UI/ChallengeCompletion.lua:111
}
time = 1
retries = 5
blizBanner = ChallengeModeCompleteBanner {
 0 = <userdata>
 Glow = Texture {
 }
 BottomFillagree = Texture {
 }
 BannerTop = Texture {
 }
 unitTokens = <table> {
 }
 timeToHold = 8
 BannerMiddle = Texture {
 }
 AnimIn = AnimationGroup {
 }
 PartyMembers = <table> {
 }
 BannerBottomGlow = Texture {
 }
 OnMouseDown = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:846
 StopBanner = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:961
 DescriptionLineThree = FontString {
 }
 BannerBottom = Texture {
 }
 PerformAnimOut = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:1022
 RightFillagree = Texture {
 }
 DescriptionLineOne = FontString {
 }
 OnLoad = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:830
 LeftFillagree = Texture {
 }
 DescriptionLineTwo = FontString {
 }
 Level = FontString {
 }
 OnEvent = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:836
 CreateAndPositionPartyMembers = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:1015
 PlayBanner = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:856
 Title = FontString {
 }
 BannerMiddleGlow = Texture {
 }
 SkullCircle = Texture {
 }
 AnimOut = AnimationGroup {
 }
 GetSortedPartyMembers = <function> defined @Blizzard_ChallengesUI/Blizzard_ChallengesUI.lua:971
 BannerTopGlow = Texture {
 }
}
challengeInfo = 399
(*temporary) = false
(*temporary) = 399
(*temporary) = "number"
(*temporary) = 1237503
(*temporary) = true
(*temporary) = 2
(*temporary) = false
(*temporary) = "attempt to get length of local 'challengeInfo' (a number value)"
ChallengeCompletion = <table> {
 createMemberRows = <function> defined @KeyMaster/Core/UI/ChallengeCompletion.lua:29
 CreateChallengeBanner = <function> defined @KeyMaster/Core/UI/ChallengeCompletionMapping.lua:231
 getDummyData = <function> defined @KeyMaster/Core/UI/ChallengeCompletionMapping.lua:11
 GetCompletionInfoWithRetries = <function> defined @KeyMaster/Core/UI/ChallengeCompletionMapping.lua:235
 ChallengeCompletionFrame = <function> defined @KeyMaster/Core/UI/ChallengeCompletion.lua:111
}
KeyMaster = <table> {
 spairs = <function> defined @KeyMaster/Libs/Internal/Misc.lua:10
 FormatDurationSec = <function> defined @KeyMaster/Libs/Internal/Misc.lua:53
 RoundToOneDecimal = <function> defined @KeyMaster/Libs/Internal/Misc.lua:333
 CreateDefaultCharacterData = <function> defined @KeyMaster/Libs/Internal/Misc.lua:160
 TPrint = <function> defined @KeyMaster/Libs/Internal/Misc.lua:34
 WeekTime = <function> defined @KeyMaster/Libs/Internal/Schedule.lua:19
 LOAD_SAVED_GLOBAL_VARIABLES = <function> defined @KeyMaster/Libs/Internal/Misc.lua:246
 _ErrorMsg = <function> defined @KeyMaster/Libs/Internal/Misc.lua:143
 PlayerFrameMapping = <table> {
 }
 Factory = <table> {
 }
 Commands = <table> {
 }
 CharacterData = <table> {
 }
 VersionCompare = <function> defined @KeyMaster/Libs/Internal/Misc.lua:340
 RoundSingleDecimal = <function> defined @KeyMaster/Libs/Internal/Misc.lua:105
 FindLastVisiblePlayerRow = <function> defined @

**Comment by Puresyn** [comment]
This branch is not ready for testing - if it even makes it too testing. Please use the release version.

**Comment by Hollicsh** [comment]
I just decided to try it.
No problem.

**Comment by Puresyn** [comment]
Minor patch branches are often full of bugs. I never recommend using them until a call to test is announced.
