### ISSUE TITLE
Incorrect potential rating gain for member on party screen.

### ISSUE THREAD

**Issue by Puresyn** [Puresyn/KeyMaster#48]
**Describe the bug**
Party screen - Group has a +10 BH Tyrannical key, one player "Mogur" has a +11 Tyrannical completed. Mogur's potential rating gain shown for the +10 key is 85.2 and should be 0.

**To Reproduce**
Unknown at this point.

**Expected behavior**
Potential rating gain for said key should be 0.

**Screenshots**
![potential_rating_gain_issue](https://github.com/Puresyn/KeyMaster/assets/10945204/62a7a29f-270e-432c-827c-edc992051aad)

**Additional context**
German Client
Submitted on behalf of Tómmy in the Key Master Discord.

**Comment by jcorrington** [comment]
@Puresyn Should this issue be closed at this time?

**Comment by Puresyn** [comment]
Will not be addressed at this time - closing.
