### ISSUE TITLE
An error appears when you log in

### ISSUE THREAD

**Issue by BlueNightSky** [Puresyn/KeyMaster#60]
**Describe the bug**
1x KeyMaster/Core/UI/MainFrame.lua:7: attempt to index local 'frame' (a nil value)
[string "@KeyMaster/Core/UI/MainFrame.lua"]:7: in function <KeyMaster/Core/UI/MainFrame.lua:6>
[string "@KeyMaster/Core/UI/MainFrame.lua"]:66: in function <KeyMaster/Core/UI/MainFrame.lua:56>

Locals:
frame = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'frame' (a nil value)"

**To Reproduce**
An error appears when you log in

**Comment by Puresyn** [comment]
Need more details on this occurrence.

Are you on the current release of KM?
Is this still happening?
Have you tried deleting the config file located at 
[DRIVE]:\Games\World of Warcraft\_retail_\WTF\Account\[ACCOUNT_NAME]\SavedVariables\KeyMaster.lua and logging in again?
Have you tried disabling all other addons except Key Master and see if the error still persists?

If yes to all the above:
Client Language
Character level
Zone
Special status when logging in such as: In Combat, In resting zone
Any other possible initiators of this error.

Thanks!

**Comment by BlueNightSky** [comment]
Have you tried deleting the config file located at
[DRIVE]:[FILE_LOCATION]\World of Warcraft_retail_\WTF\Account[ACCOUNT_NAME]\SavedVariables\KeyMaster.lua and logging in again?
After deleting the file, no more error, tks!
