### ISSUE TITLE
(1.2.4) Dungeon rating values show 0 rating when they shouldn't upon login.

### ISSUE THREAD

**Issue by Puresyn** [Puresyn/KeyMaster#63]
**Describe the bug**
When first logging into a character, the individual dungeon ratings show 0 for the logged in character but are correct for characters in the "characters" list.
Using /reload corrects the issue.
Any  time you fully exit the game, the character you log into shows 0s for all dungeon ratings (but overall for last season is correct).

**To Reproduce**
Log (from a fresh game launch) into any character with a DF S4 M+ dungeon rating.
Open Key Master and view the  party or character screen.
The currently active character's individual dungeon scores are all 0s - even when they shouldn't be.
Other characters in the "characters" list show dungeon ratings properly.
Using /reload fixes the ratings for the active character.
Exiting the game and selecting a character with a rating starts the issue over again.

**Expected behavior**
Individual dungeon ratings should be displayed correctly at all times.

**Screenshots**
Incorrect:
![image](https://github.com/user-attachments/assets/79b1742e-78a9-494e-8dc0-c6a187efb2b9)
Correct:
![image](https://github.com/user-attachments/assets/12174fd6-8f84-405a-b58e-e5657a1c90ac)

**Additional context**
There is a high likelihood that this is a result of being between seasons and the API returning nil on some queries.

**Comment by MoarCoffee** [comment]
Always showing 0 for me, despite reloading.

**Comment by Puresyn** [comment]
> Always showing 0 for me, despite reloading.

This is due to the major Mythic plus rating changes that Blizzard made in The War Within. These issues are being addressed in the next release of Key Master (1.3.0).

**Comment by MoarCoffee** [comment]
Is there an alpha build where it is fixed?

**Comment by Puresyn** [comment]
> Is there an alpha build where it is fixed?

With a little luck, 1.3.0 will be released today.

**Comment by Puresyn** [comment]
KM 1.3.0 has been released. Closing this issue.
