### ISSUE TITLE
chat shortcut not working

### ISSUE THREAD

**Issue by Quasanar** [Puresyn/KeyMaster#66]
**Describe the bug**
/km or /keymaster does nothing

**To Reproduce**
type /km or /keymaster in the chatbox 
Nothing shows up

**Expected behavior**
Should open the addon interface

**Comment by Puresyn** [comment]
Try disabling all other addons and see if the issue persists (also make sure Key Master in enabled in your addons).

**Comment by Quasanar** [comment]
I tried that. Even created a fresh character with only Key Master enabled but the problem persists.

**Comment by Puresyn** [comment]
> I tried that. Even created a fresh character with only Key Master enabled but the problem persists.

Not sure what it would be. We haven't had anyone else mention this. Try going into your game key binds and bind Key Master to a key. Also, you can click on the minimap icon. If you can't find or see either of those options, then key master is not loading for you.

**Comment by Quasanar** [comment]
![Screenshot 2024-09-22 040858](https://github.com/user-attachments/assets/597f0855-93fb-41f2-afcf-762208f4e4dc)

Yeah its weird , i included this screenshot where you see that it is enabled but i dont have the minimap button , even when disabling everything except Key Master

**Comment by Quasanar** [comment]
I also just installed an addon through the same process as Key Master called "mogit" that i never had on my account and that works just fine.

**Comment by Puresyn** [comment]
I've located what I believe to be the issue. version 1.3.1 should fix it.

**Comment by Puresyn** [comment]
Curseforge is having issues taking the update. You can grab v1.3.1 on our Discord in the general chat until it works there. https://discord.gg/bbMaUpfgn8
