### ISSUE TITLE
See score gain for all dungeons for a specific keylevel

### ISSUE THREAD

**Issue by MarcLFJ** [Puresyn/KeyMaster#69]
**Is your feature request related to a problem? Please describe.**
Just a nice to have feature. Previously used [Mythic Plus Rating Gain](https://www.curseforge.com/wow/addons/mythic-plus-rating-gain) for this, but hasn't been updated for the expansion.

**Describe the solution you'd like**
Like the feature on the `player` tab to check gain for 1 dungeon for a specific keylevel, but have an option to see gain for dungeons for a specific level.

**Describe alternatives you've considered**
Only cway currently afaik is to manually check for each key

**Additional context**
No

**Comment by Puresyn** [comment]
Thanks for the feature request, we'll keep it in mind! In the mean time: every on par dungeon run has a default value that is the same across all dungeons and levels. For instance: +2s are worth 150 rating each (if you run in faster than it is worth more of course). So, 8 dungeons x 150 rating = 1,200 rating for all 2s. Once you get to higher keys, you can take that overall key level base rating and subtract your own overall rating, that would give you the number you seek.

If you want to know the base for a certain levels, log into any character without a rating, open Key Master and put in a key level (map doesn't matter). Multiply that by 8 and there is the base rating for all dungeons at that level.

Hope that helps!
Thanks!

**Comment by Puresyn** [comment]
We'll keep this in mind for future versions - closing for archive.
