### ISSUE TITLE
KM doesn't think I completed a 10 DB, but I did

### ISSUE THREAD

**Issue by phay2thedre** [Puresyn/KeyMaster#74]
I completed a 10 Dawnbreaker last night (we didn't time it, but it was completed) but KM is currently still showing I have completed a +9. 

I uploaded a log from last night to make sure we did complete it. 
https://www.warcraftlogs.com/reports/gTb3F6V7KtzZrNCQ#fight=last

I updated the raider.io app about an hour ago to see if maybe that would help. 

![image](https://github.com/user-attachments/assets/5e6d397a-5797-4caf-9ebd-b2a54b96ae09)
Here's a screenshot of KM in the game currently.

**Comment by jcorrington** [comment]
This is being fixed in the release today.  Sorry for the delay!
