### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by vj234013** [Puresyn/KeyMaster#75]
Interface/AddOns/KeyMaster/KeyMaster.lua:18: attempt to index global 'KeyMasterLocals' (a nil value)
Count: 1

Call Stack:
[1] [string "@Interface/AddOns/KeyMaster/KeyMaster.lua"]:18: in main chunk

**Comment by vj234013** [comment]
.../AddOns/KeyMaster/Core/Localization/Localization.lua:78: attempt to index global 'KeyMasterLocals' (a nil value)
Count: 1

Call Stack:
[1] [string "@Interface/AddOns/KeyMaster/Core/Localization/Localization.lua"]:78: in main chunk

**Comment by vj234013** [comment]
Interface/AddOns/KeyMaster/KeyMaster.lua:18: attempt to index global 'KeyMasterLocals' (a nil value)
Count: 1

Call Stack:
[1] [string "@Interface/AddOns/KeyMaster/KeyMaster.lua"]:18: in main chunk

**Comment by vj234013** [comment]
My language is Simplified Chinese

**Comment by vj234013** [comment]
This plug-in has no problem since version 1.3.4. It has problems since version 1.3.5.

**Comment by Puresyn** [comment]
Here is what changed. Do you see any problems/issues? https://github.com/Puresyn/KeyMaster/commit/07b0eda16038b72ae1dba3d6179723c08889ecef

**Comment by vj234013** [comment]
Sorry, I don't know how to program. I replaced version 1.3.4 with the zhCN.lua file from version 1.3.6 and it works fine.Replacing the two issues in 1.3.6 with the file in 1.3.4 will still result in an error. So I guess it's not the file you asked me about that had a problem

**Comment by Puresyn** [comment]
> Sorry, I don't know how to program. I replaced version 1.3.4 with the zhCN.lua file from version 1.3.6 and it works fine.Replacing the two issues in 1.3.6 with the file in 1.3.4 will still result in an error. So I guess it's not the file you asked me about that had a problem (My English is not good. The translation software used Please forgive me)

Thanks, we will look into it.

**Comment by Puresyn** [comment]
I've located the problem.

KeyMaster/Core/Localization/Languages.xml Line 12 should not be commented out.
Incorrect: 
Correct: <Script file='Core\Localization\Localization.zhCN.lua'/>

It was an oversight on my behalf since we lost our CN translator. Apologies. It will be fixed in the next patch.

**Comment by vj234013** [comment]
Thank you very much. I manually made the necessary changes based on the issue you mentioned It's alright now! Thanks again!

**Comment by vj234013** [comment]
1.3.4
![image](https://github.com/user-attachments/assets/213b0242-e1c4-4f62-8955-55c9fc41ffc1)

**Comment by vj234013** [comment]
1.3.6
![image](https://github.com/user-attachments/assets/65f5714f-f29c-44fd-8814-a48c6bbeb3ea)

**Comment by vj234013** [comment]
The 1.3.6 version was manually modified according to the location you mentioned, and now it looks like this in the game A piece is empty

**Comment by Puresyn** [comment]
> 1.3.6 ![image](https://private-user-images.githubusercontent.com/165003204/380962222-65f5714f-f29c-44fd-8814-a48c6bbeb3ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxNzM0MzYsIm5iZiI6MTczMDE3MzEzNiwicGF0aCI6Ii8xNjUwMDMyMDQvMzgwOTYyMjIyLTY1ZjU3MTRmLWYyOWMtNDRmZC04ODE0LWE0OGM2YmJlYjNlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOVQwMzM4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODRhMDEwZjc2Y2UyODlmMTBjN2ZlMzVkYTUwOGI0NWJlMDk3YWEyY2FlZDFlN2FkM2U5NWY4MmIzMmI3NDU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JnL0sal6rZPTB8zSSkSNSOc7BGL3q1u-qKN0oqpiNTs)

this is correct

**Comment by vj234013** [comment]
Has the explanation of affixes been removed here?

**Comment by Puresyn** [comment]
> Has the explanation of affixes been removed here?

Moved to tooltips - Hover over affix icon in header.

**Comment by vj234013** [comment]
Ok, I got it. Thanks again. Wishing the plugin continued improvement
