### ISSUE TITLE
Bug: Completed three 11s this week but Key Master only shows one 11 key

### ISSUE THREAD

**Issue by phay2thedre** [Puresyn/KeyMaster#78]
**Describe the bug**
I completed three 11 keys this week but there's only one 11 appearing in my list of dungeons.

**To Reproduce**
Open Key Master
Navigate to Characters tab and click on toon's name (or just click on Player tab)
Look at M+ Vault Progression box and see there are three 11s completed this week (on the prior day 12/15)
Look at list of timed dungeons and see there is only one 11 appearing

**Expected behavior**
I expected to see 11s for Siege, Mists, and City of Echoes on this screen, but I only see one 11 (for Siege.)

**Screenshots**

![screenshot-key-master-phaydragosa-completed-3-11s-this-week](https://github.com/user-attachments/assets/6114a27d-3ae7-4b61-bd47-141e6424b386)

![screenshot-key-master-phaydragosa-party-window](https://github.com/user-attachments/assets/61f4ed13-f0b5-4351-b342-720f7e0312b0)

**Additional context**
Dungeon logs 
https://www.warcraftlogs.com/reports/V8AYTWjQLpDJ1qCP?fight=3
https://www.warcraftlogs.com/reports/V8AYTWjQLpDJ1qCP?fight=6
https://www.warcraftlogs.com/reports/V8AYTWjQLpDJ1qCP?fight=7

**Comment by Puresyn** [comment]
Curious - I'm assuming this is the character you were logged into at the time and reloading or relogging didn't change anything?

**Comment by phay2thedre** [comment]
> Curious - I'm assuming this is the character you were logged into at the time and reloading or relogging didn't change anything?

Yes I was logged into that toon when I took the screenshot and reloading hasn't changed it. Tried both solo and while in a party.

**Comment by Puresyn** [comment]
Very strange. The only thing I can suggest to try is purging all your data on the configuration tab and relogging Maybe something got corrupted?

**Comment by phay2thedre** [comment]
(Score went up to 2567 between the previous screenshot and this one because I did a couple of 10s last night.) This evening I clicked on Purge Characters while I was on Phaydragosa and relogged onto Phaydragosa but it was still showing only one 11 key done. I tried hopping on a different toon and purging the characters then hopping onto Phaydragosa but it's still showing the same as before I purged. 

![screenshot-key-master-phaydragosa-12-17-2024](https://github.com/user-attachments/assets/aca108c9-6908-47fe-9bdc-08aea56ef402)

**Comment by Puresyn** [comment]
per raider.io - you didn't time those in enough time to get rating so they are not listed out in rating calculations.
![image](https://github.com/user-attachments/assets/550653a1-993d-4009-979d-ced90980c023)

**Comment by phay2thedre** [comment]
Makes sense. I recommend adding help text on that screen to clarify what determines whether a key appears there so the person knows it's working correctly and not a bug, like I thought. :)
